spring:
  datasource:
    name: campus  #数据库名
    url: jdbc:mysql://localhost:3306/campus?allowMultiQueries=true #url
    username: root  #用户名
    password: root  #密码
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    static-locations: file:src/main/resources/static/


mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.sevengroup.campus.bean #配置实体类
